### ISSUE TITLE
Optimisation import font google 

### ISSUE THREAD

**Issue by Grezor** [Caro-L-dev/TP-Html-Css#1]
https://github.com/Caro-L-dev/TP-Html-Css/blob/593eb086d3d861b157d0b85699da29b2027be346/assets/css/styles.css#L2

Hello,
Il y a la possibilité d'optimiser l'import de Google font, en créant un dossier font. Et télécharger les fonts, puis appeler directement le dossier + le fichier dans le css

 exemple : 
```
@font-face {
   font-family: myfont;
   src: url(sansation_light.woff);
}

* {
   font-family: myfont;
}
```

**Comment by Caro-L-dev** [comment]
Yup merci du conseil mais là n'était point le but premier
